version: '3'
services:
  db:
    image: 'postgres:latest'
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nodejs
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
